language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# command to install dependencies
install: "pip install -r requirements.txt"
#install: "pip install numpy"

# command to run tests
script: python tests/test.py

notifications:
  slack: koitaroh:wibfYrcZ4S9wsXJYvyIN9vYI